version: "3"

networks:
  db:
    internal: true

volumes:
  moca_db:
    driver: local
  moca_modules:
    driver: local

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    volumes:
      - moca_db:/var/lib/postgresql/data:rw
    networks:
      - db
    expose:
      - 5432:5432
    tty: true
    restart: no
  node:
    image: node:20
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - TZ=UTC
    volumes:
      - ./:/moca
      - moca_modules:/moca/node_modules
    tmpfs: /moca-tmp
    depends_on:
      - db
    networks:
      - db
    ports:
      - 8080:8080
    command: >
      bash -c "cd /moca &&
      npm install -g pnpm &&
      pnpm i &&
      pnpm run start"
    tty: true
    restart: no
