version: "3"

volumes:
  db:
    driver: local

networks:
  db:
    internal: true
  app:
    internal: false

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    networks:
      - db
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    tty: true
    restart: always

  moca:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - TZ=UTC
    working_dir: "/moca"
    tmpfs: /moca-tmp
    networks:
      - db
      - app
    ports:
      - 8122:8080
    depends_on:
      - db
    command: "pnpm run start"
    tty: true
    restart: always
