version: "3"

volumes:
  db:
    driver: local

networks:
  internal_net:
    internal: true
  external_net:
    internal: false

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC
    networks:
      - internal_net
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    tty: true
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - TZ=UTC
    working_dir: "/moca"
    tmpfs: /moca-tmp
    networks:
      - internal_net
    expose:
      - 8080
    depends_on:
      - db
    command: "pnpm run start"
    tty: true
    restart: always

  tunnel:
    image: cloudflare/cloudflared:latest
    env_file:
      - config.env
    environment:
      - TZ=Asia/Tokyo
    networks:
      - internal_net
      - external_net
    command: tunnel run
    tty: true
    restart: always
